services:
  cloudflared:
    image: docker.io/cloudflare/cloudflared:latest
    restart: always
    command: tunnel --no-autoupdate run --token ${CLOUDFLAREDTOKEN}
    environment:
      - CLOUDFLAREDTOKEN=${CLOUDFLAREDTOKEN}
    networks:
      - kaffino-network
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      PORT: ${PORT}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
    volumes:
      - ./db:/app/db
    networks:
      - kaffino-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 3000:3000
    depends_on:
      - backend
    networks:
      - kaffino-network

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 8000:8000
    depends_on:
      - frontend
      - backend
    networks:
      - kaffino-network

networks:
  kaffino-network:
    driver: bridge
    
volumes:
  sqlite_bp:

