services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      APP_ENV: ${APP_ENV}
      PORT: ${PORT}
      BLUEPRINT_DB_URL: ${BLUEPRINT_DB_URL}
    volumes:
      - ./db:/app/db
    networks:
      - kaffino-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 3000:3000
    depends_on:
      - backend
    networks:
      - kaffino-network

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 8000:8000
    depends_on:
      - frontend
      - backend
    networks:
      - kaffino-network

networks:
  kaffino-network:
    driver: bridge
    
volumes:
  sqlite_bp:

