services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    restart: unless-stopped
    ports:
      - ${PORT}:${PORT}
    environment:
      APP_ENV: ${APP_ENV}
      PORT: ${PORT}
      BLUEPRINT_DB_URL: ${BLUEPRINT_DB_URL}
    volumes:
      - sqlite_bp:/app/db
  frontend:
    build:
      context: ./frontend
    restart: unless-stopped
    ports:
      - 3000:3000
    depends_on:
      - app
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
      target: nginx
    restart: unless-stopped
    ports:
      - 80:80
    depends_on:
      - app
      - frontend
volumes:
  sqlite_bp:
    ./db
